workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - when: never

stages:
  - validate
  - package

default:
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

validate:
  stage: validate
  rules:
    - when: manual
  script:
    - npm run audit:ci
    - npm run lint
    - npx tsc -p tsconfig.json --noEmit
    - npm run test:unit
    - npm run build

package:
  stage: package
  needs:
    - validate
  rules:
    - when: manual
  script:
    - npm run build:prod
    - npm run package
    - npm run check:bundle-size
  artifacts:
    name: kicadstudio-vsix-$CI_COMMIT_REF_SLUG
    paths:
      - '*.vsix'
    expire_in: 14 days
