# public-hygiene-scan.ps1
# Private scanner. Run from the root of a target repository.
# Usage:
#   pwsh -ExecutionPolicy Bypass -File path\to\public-hygiene-scan.ps1

$ErrorActionPreference = "Continue"

$Patterns = @(
    "wow effect",
    "principal-level transformation",
    "principle-level transformation",
    "generated by ai",
    "created by ai",
    "created by claude",
    "created by chatgpt",
    "claude prompt",
    "chatgpt prompt",
    "prompt used",
    "share this on twitter",
    "post this on x",
    "open an account",
    "todo for user",
    "next you should",
    "ask the owner",
    "owner should",
    "ai-generated",
    "agent made"
)

$Failed = $false

foreach ($Pattern in $Patterns) {
    $Matches = git grep -n -i -- "$Pattern" 2>$null
    if ($Matches) {
        Write-Host "Violation pattern: $Pattern" -ForegroundColor Red
        Write-Host $Matches
        $Failed = $true
    }
}

if ($Failed) {
    Write-Host "Public hygiene scan failed." -ForegroundColor Red
    exit 1
}

Write-Host "Public hygiene scan passed." -ForegroundColor Green
